### ISSUE TITLE
GenServer terminating on timeout

### ISSUE THREAD

**Issue by DmitryPopov** [Flying-Toast/yugo#9]
Getting next error time to time:
`04:06:50.646 [error] GenServer {Yugo.Registry, :mail_client} terminating
** (FunctionClauseError) no function clause matching in Yugo.Parser.parse_untagged_with_status/2
    (yugo 0.3.1) lib/yugo/parser.ex:98: Yugo.Parser.parse_untagged_with_status("timeout", :bye)
    (yugo 0.3.1) lib/yugo/client.ex:266: Yugo.Client.handle_packet/2
    (yugo 0.3.1) lib/yugo/client.ex:184: Yugo.Client.handle_info/2
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:ssl, {:sslsocket, {:gen_tcp, #Port<0.144>, :tls_connection, :undefined}, [#PID<0.2781.0>, #PID<0.2780.0>]}, "* BYE timeout\r\n"}`

**Comment by Flying-Toast** [comment]
Thanks for reporting this. The IMAP spec requires servers with such “timeout” features MUST have a timeout of at least 30 minutes - Yugo should send a heartbeat every 27 minutes. Could you measure how long it’s taking you to get the timeouts?
Also, what mail server are you connecting to?

**Comment by Flying-Toast** [comment]
@DmitryPopov Any update? If not I'm gonna close this issue.
